#include <buddy/Core/Container.h>
#include <string>
#include <iostream>
#include <filesystem>
#include <cstdint>
#include <cmath>
#include <cstring>
#include <cassert>

using fp16_t = uint16_t;

extern "C" void _mlir_ciface_forward(MemRef<fp16_t, 2> *, MemRef<fp16_t, 2> *);

// ----------------- Float16<->Float32 conversion utils ----------------------

static inline float fp32_from_bits(uint32_t w) {
    union {
        uint32_t as_bits;
        float as_value;
    } fp32;
    fp32.as_bits = w;
    return fp32.as_value;
}

static inline uint32_t fp32_to_bits(float f) {
    union {
        float as_value;
        uint32_t as_bits;
    } fp32;
    fp32.as_value = f;
    return fp32.as_bits;
}

static fp16_t fp32_to_fp16(float f) {
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L) || defined(__GNUC__) && !defined(__STRICT_ANSI__)
    const float scale_to_inf = 0x1.0p+112f;
    const float scale_to_zero = 0x1.0p-110f;
#else
    const float scale_to_inf = fp32_from_bits(UINT32_C(0x77800000));
    const float scale_to_zero = fp32_from_bits(UINT32_C(0x08800000));
#endif
    float base = (std::fabs(f) * scale_to_inf) * scale_to_zero;

    const uint32_t w = fp32_to_bits(f);
    const uint32_t shl1_w = w + w;
    const uint32_t sign = w & UINT32_C(0x80000000);
    uint32_t bias = shl1_w & UINT32_C(0xFF000000);
    if (bias < UINT32_C(0x71000000)) {
        bias = UINT32_C(0x71000000);
    }

    base = fp32_from_bits((bias >> 1) + UINT32_C(0x07800000)) + base;
    const uint32_t bits = fp32_to_bits(base);
    const uint32_t exp_bits = (bits >> 13) & UINT32_C(0x00007C00);
    const uint32_t mantissa_bits = bits & UINT32_C(0x00000FFF);
    const uint32_t nonsign = exp_bits + mantissa_bits;
    return (sign >> 16) | (shl1_w > UINT32_C(0xFF000000) ? UINT16_C(0x7E00) : nonsign);
}

static float fp16_to_fp32(fp16_t h) {
    const uint32_t w = (uint32_t) h << 16;
    const uint32_t sign = w & UINT32_C(0x80000000);
    const uint32_t two_w = w + w;

    const uint32_t exp_offset = UINT32_C(0xE0) << 23;
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L) || defined(__GNUC__) && !defined(__STRICT_ANSI__)
    const float exp_scale = 0x1.0p-112f;
#else
    const float exp_scale = fp32_from_bits(UINT32_C(0x7800000));
#endif
    const float normalized_value = fp32_from_bits((two_w >> 4) + exp_offset) * exp_scale;

    const uint32_t magic_mask = UINT32_C(126) << 23;
    const float magic_bias = 0.5f;
    const float denormalized_value = fp32_from_bits((two_w >> 17) | magic_mask) - magic_bias;

    const uint32_t denormalized_cutoff = UINT32_C(1) << 27;
    const uint32_t result = sign |
        (two_w < denormalized_cutoff ? fp32_to_bits(denormalized_value) : fp32_to_bits(normalized_value));
    return fp32_from_bits(result);
}


// ----------------- Workaround for undefined symbols ------------------- //

#define ATTR_WEAK __attribute__((__weak__))
// Provide a float->float16 conversion routine in case the runtime doesn't have
// one.
extern "C" fp16_t ATTR_WEAK __truncsfhf2(float f) {
  fp16_t hf = fp32_to_fp16(f);
  // The output can be a float type, bitcast it from uint16_t.
  fp16_t ret = 0;
  std::memcpy(&ret, &hf, sizeof(hf));
  std::cout << "from float: " << f << std::endl;
  return ret;
}

// Provide a float16->float conversion routine in case the runtime doesn't have
// one.
extern "C" float ATTR_WEAK __extendhfsf2(fp16_t hf) {
  float f = fp16_to_fp32(hf);
  std::cout << "to float: " << f << std::endl;
  return f;
}

int main() {
  /// Print the title of this example.
  const std::string title = "Pow w/ Float16 Generated by Buddy Compiler";
  std::cout << "\033[33;1m" << title << "\033[0m" << std::endl;

  // check conversion utils
  assert(std::fabs(__extendhfsf2(__truncsfhf2(0.5f)) - 0.5f) < 1e-5);

  /// Initialize data containers
  MemRef<fp16_t, 2> inputContainer({2, 2}, fp32_to_fp16(0.5f));
  MemRef<fp16_t, 2> resultContainer({2, 2}, fp32_to_fp16(999.f));

  // Execute the forward pass of the model.
  _mlir_ciface_forward(&resultContainer, &inputContainer);

  /// Print the final result
  // get 0.5 normally
  std::cout << "\n\033[33;1m[Input]\033[0m " << fp16_to_fp32(inputContainer.getData()[0]) << std::endl;
  // exptected 0.125 but get 0
  std::cout << "\033[33;1m[Output]\033[0m " << fp16_to_fp32(resultContainer.getData()[0]) << std::endl;

  return 0;
}