#include <buddy/Core/Container.h>
#include <string>
#include <iostream>
#include <filesystem>
#include <cstdint>
#include <cmath>
#include <cstring>
#include <cassert>


extern "C" void _mlir_ciface_forward(MemRef<float, 2> *, MemRef<float, 2> *);


int main() {
  /// Print the title of this example.
  const std::string title = "Pow w/ Float32 Generated by Buddy Compiler";
  std::cout << "\033[33;1m" << title << "\033[0m" << std::endl;

  /// Initialize data containers
  MemRef<float, 2> inputContainer({2, 2}, 0.5f);
  MemRef<float, 2> resultContainer({2, 2}, 999.f);

  // Execute the forward pass of the model.
  _mlir_ciface_forward(&resultContainer, &inputContainer);

  /// Print the final result
  // get 0.5 normally
  std::cout << "\n\033[33;1m[Input]\033[0m " << inputContainer.getData()[0] << std::endl;
  // get 0.125 normally
  std::cout << "\033[33;1m[Output]\033[0m " << resultContainer.getData()[0] << std::endl;

  return 0;
}